# Configuration for Pyrogram
[pyrogram]
session_name = session/video_repurpose_bot_client
api_id       = 0000000
api_hash     = 00000000000000000000000000000000
bot_token    = 0000000000:AAAAAAAAAAAA-0000000000000000000000

[app]
app_support = username
app_admin_users = username1,username2,...
app_auth_users = username3,username4,...
# Example with custom translation
#app_lang_file = lang/lang_it.xml

[video]
video_max_processes = 2
video_download_folder = video/download/
video_download_delete_file = True
video_process_folder = video/proc/
video_process_delete_file = True
video_ffmpeg_params_file = conf/ffmpeg_params.ini
video_ffmpeg_filters_doc_url = https://ffmpeg.org/ffmpeg-filters.html

[logging]
log_file_enabled = True
log_file_name = logs/video_repurpose_bot.log
log_file_use_rotating = True
log_file_max_bytes = 5242880
log_file_backup_cnt = 10
